#!/bin/bash
source .env

VER="$VERSION"
REG="$REGISTRY"
BTAG="$TAG"
GSRC="$GAME_SRC"
GDST="$GAME_DST"

if [ "$1" != "" ]; then
  VER=$1
fi

./update-game-folder

docker compose build app-prod

if [ $? -eq 0 ]; then
	read -p "Deploy to registry ($REG) [y/n]: " YN
	if [ "$YN" == "y" ]; then
		docker tag $BTAG $REG/$BTAG:$VER && \
		docker push $REG/$BTAG:$VER
	fi
fi
