#FROM: https://blog.cloudboost.io/developing-angular-applications-using-docker-6f4835a75195

ARG NODE_VERSION

FROM node:${NODE_VERSION} AS build
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app/
RUN ["npm", "install"]
COPY . /app
RUN ["npm", "run","build","--prod"]

FROM nginx:alpine
COPY --from=build /app/dist/IAsRevenge/browser /usr/share/nginx/html

EXPOSE 80/tcp
CMD ["nginx", "-g", "daemon off;"]