#!/bin/bash
source .env

GSRC="$GAME_SRC"
GDST="$GAME_DST"

if [ "$GDST" == "" ]; then
	echo "Invalid GDST"
	exit -1
fi	

if [ ! -d "$GDST" ]; then
   mkdir -p $GDST
fi

if [ -d "$GAME_SRC" ]; then
	read -p "Update game files [y/n]: " YN
	if [ "$YN" == "y" ]; then
		rm -rf $GDST/*
		cp -r $GSRC/* $GDST
   else
      read -p "Delete game file [y/n]: " YN
      if [ "$YN" == "y" ]; then
		   rm -rf $GDST/*
      fi
	fi
fi
